baseURL: https://benedictpak.com
languageCode: en-us
title: Benedict Pak
theme: PaperMod
enableEmoji: true

googleAnalytics: UA-143052141-1

menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 1
    - identifier: blog
      name: Blog
      url: /blog/
      weight: 2
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 3
    - identifier: linkedin
      name: LinkedIn
      url: https://www.linkedin.com/in/benedictpak
      weight: 4
    - identifier: github
      name: GitHub
      url: https://github.com/Nanosync
      weight: 5

params:
  title: "Benedict Pak"
  description: "Benedict Pak's developer portfolio."
  keywords: ["Benedict Pak", "Developer", "Portfolio"]
  images: ["logo.png"]
  DateFormat: "2 January 2006"

  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: "I'm **Benedict Pak**. I love tinkering with software and learning about how things work."
  socialIcons:
    - name: linkedin
      url: "https://www.linkedin.com/in/benedictpak"
    - name: github
      url: "https://github.com/Nanosync"

  profileMode:
    enabled: true
    title: Benedict Pak
    subtitle: "I love tinkering with software and learning about how things work."

  ShowReadingTime: true
  ShowShareButtons: true
  ShareButtons: ["linkedin", "twitter", "reddit", "facebook"]
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: false
  ShowRssButtonInSectionTermList: false
  UseHugoToc: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
